// Sample contacts data — HVAC industry (Izzat Marji Group context)

window.CONTACTS = [
  { id: 'C-1042', name: 'Tariq Al-Sayed',     role: 'Facilities Director',  company: 'Royal Jordanian',         email: 'tariq.alsayed@rj.com',          phone: '+962 6 510 0123', city: 'Amman',  tags: ['VIP', 'Key account'], lastContact: '2 days ago',  owner: 'Hala Jaber',     deals: 3, status: 'active' },
  { id: 'C-1043', name: 'Reem Khoury',         role: 'Procurement Manager',  company: 'Abdali Mall',             email: 'r.khoury@abdalimall.jo',        phone: '+962 6 520 4811', city: 'Amman',  tags: ['Decision maker'],     lastContact: '5 hours ago',  owner: 'Omar Najjar',    deals: 2, status: 'active' },
  { id: 'C-1044', name: 'Yousef Mansour',      role: 'Chief Engineer',       company: 'King Hussein Cancer Ctr', email: 'y.mansour@khcc.jo',             phone: '+962 6 530 0090', city: 'Amman',  tags: ['Technical'],          lastContact: 'Yesterday',    owner: 'Hala Jaber',     deals: 1, status: 'active' },
  { id: 'C-1045', name: 'Lina Haddad',         role: 'CFO',                  company: 'Zara Investment Holding', email: 'lina.h@zara.com.jo',            phone: '+962 6 565 1200', city: 'Amman',  tags: ['VIP'],                lastContact: '1 week ago',   owner: 'Sami Odeh',      deals: 4, status: 'active' },
  { id: 'C-1046', name: 'Khalid Bani-Hani',    role: 'Operations Manager',   company: 'Aqaba Container Terminal', email: 'khalid.bh@act.jo',             phone: '+962 3 209 0011', city: 'Aqaba',  tags: [],                     lastContact: '3 days ago',   owner: 'Omar Najjar',    deals: 1, status: 'active' },
  { id: 'C-1047', name: 'Noor Al-Masri',       role: 'Project Lead',         company: 'Eagle Hills Jordan',      email: 'noor.almasri@eaglehills.jo',    phone: '+962 6 580 7700', city: 'Amman',  tags: ['Decision maker'],     lastContact: '4 days ago',   owner: 'Hala Jaber',     deals: 2, status: 'active' },
  { id: 'C-1048', name: 'Mohammad Sweidan',    role: 'Maintenance Head',     company: 'Marriott Petra',          email: 'm.sweidan@marriott.com',        phone: '+962 3 215 6611', city: 'Petra',  tags: ['Technical'],          lastContact: '2 weeks ago',  owner: 'Sami Odeh',      deals: 1, status: 'inactive' },
  { id: 'C-1049', name: 'Dana Tabbaa',         role: 'GM',                   company: 'Tabbaa Real Estate',      email: 'dana@tabbaa-re.com',            phone: '+962 6 590 1100', city: 'Amman',  tags: ['Key account', 'VIP'], lastContact: 'Today',        owner: 'Hala Jaber',     deals: 5, status: 'active' },
  { id: 'C-1050', name: 'Faris Abdo',          role: 'Site Engineer',        company: 'Bayan Construction',      email: 'f.abdo@bayan.jo',               phone: '+962 6 575 4422', city: 'Irbid',  tags: ['Technical'],          lastContact: '6 days ago',   owner: 'Omar Najjar',    deals: 1, status: 'active' },
  { id: 'C-1051', name: 'Salma Qaddoumi',      role: 'Procurement',          company: 'Jordan University Hospital', email: 's.qaddoumi@juh.edu.jo',     phone: '+962 6 535 3220', city: 'Amman',  tags: [],                     lastContact: '3 weeks ago',  owner: 'Sami Odeh',      deals: 0, status: 'inactive' },
  { id: 'C-1052', name: 'Anas Khateeb',        role: 'CTO',                  company: 'Mawared Holding',         email: 'anas.k@mawared.jo',             phone: '+962 6 555 9090', city: 'Amman',  tags: ['Decision maker'],     lastContact: '8 hours ago',  owner: 'Hala Jaber',     deals: 2, status: 'active' },
  { id: 'C-1053', name: 'Hadeel Saadeh',       role: 'Office Manager',       company: 'Saraya Aqaba',            email: 'h.saadeh@saraya.com',           phone: '+962 3 207 7700', city: 'Aqaba',  tags: [],                     lastContact: '4 days ago',   owner: 'Omar Najjar',    deals: 1, status: 'active' },
  { id: 'C-1054', name: 'Bassel Khoury',       role: 'Facilities Manager',   company: 'Boulevard Abdali',        email: 'b.khoury@boulevard.jo',         phone: '+962 6 581 1010', city: 'Amman',  tags: ['Technical'],          lastContact: '10 days ago',  owner: 'Hala Jaber',     deals: 1, status: 'active' },
  { id: 'C-1055', name: 'Maha Touqan',         role: 'Director',             company: 'Touqan Properties',       email: 'maha@touqan-prop.jo',           phone: '+962 6 591 2233', city: 'Amman',  tags: ['VIP'],                lastContact: '2 days ago',   owner: 'Sami Odeh',      deals: 2, status: 'active' },
];
